<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kent Studio</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            background-color: #0a0a0a;
            color: white;
            overflow-x: hidden;
        }

        header {
            background-color: #333;
            padding: 1rem;
            text-align: center;
            animation: fadeIn 1s ease-out;
        }

        header h1 {
            font-size: 2.5rem;
            letter-spacing: 1px;
            word-wrap: break-word;
        }

        nav {
            text-align: center;
            margin: 20px 0;
        }

        nav a {
            color: white;
            text-decoration: none;
            margin: 0 15px;
            font-size: 1.2rem;
            transition: color 0.3s ease;
        }

        nav a:hover {
            color: #f39c12;
        }

        .hero {
            background-color: #1c1c1c;
            padding: 80px 20px;
            text-align: center;
            opacity: 0;
            animation: fadeInUp 1.5s 0.5s forwards;
        }

        .hero h2 {
            font-size: 3rem;
            margin-bottom: 20px;
        }

        .hero p {
            font-size: 1.3rem;
            margin-bottom: 40px;
            word-wrap: break-word;
        }

        .btn {
            background-color: #f39c12;
            color: white;
            padding: 10px 30px;
            text-decoration: none;
            font-size: 1.1rem;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        .btn:hover {
            background-color: #e67e22;
        }

        .section {
            padding: 60px 20px;
            text-align: center;
            opacity: 0;
            animation: fadeInUp 1.5s ease-out forwards;
            word-wrap: break-word;
        }

        .about, .services, .contact {
            animation-delay: 1s;
        }

        .about h3, .services h3, .contact h3 {
            font-size: 2rem;
            margin-bottom: 20px;
        }

        .about p, .services p, .contact p {
            font-size: 1.2rem;
            max-width: 800px;
            margin: 0 auto;
        }

        .manager-buttons {
            margin-top: 40px;
        }

        .manager-buttons a {
            margin: 0 15px;
            background-color: #f39c12;
            color: white;
            padding: 15px 30px;
            text-decoration: none;
            font-size: 1.1rem;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        .manager-buttons a:hover {
            background-color: #e67e22;
        }

        footer {
            background-color: #333;
            color: white;
            text-align: center;
            padding: 20px 0;
            animation: fadeIn 1s ease-out 1.5s forwards;
        }

        /* Анимации */
        @keyframes fadeIn {
            0% {
                opacity: 0;
            }
            100% {
                opacity: 1;
            }
        }

        @keyframes fadeInUp {
            0% {
                opacity: 0;
                transform: translateY(20px);
            }
            100% {
                opacity: 1;
                transform: translateY(0);
            }
        }

        /* Анимация "печати" */
        .typing {
            display: inline-block;
            border-right: 2px solid white;
            animation: typing 5s steps(60) 1s forwards, blink 0.75s step-end infinite;
            white-space: nowrap;
            overflow: hidden;
        }

        @keyframes typing {
            from {
                width: 0;
            }
            to {
                width: 100%;
            }
        }

        @keyframes blink {
            50% {
                border-color: transparent;
            }
        }

        /* Адаптивность */
        @media (max-width: 768px) {
            header h1 {
                font-size: 2rem;
            }

            .hero h2 {
                font-size: 2.5rem;
            }

            .hero p {
                font-size: 1.2rem;
            }

            .section h3 {
                font-size: 1.5rem;
            }

            .manager-buttons a {
                padding: 10px 20px;
                font-size: 1rem;
            }

            .about p, .services p, .contact p {
                font-size: 1rem;
                max-width: 90%;
            }
        }

        /* Для маленьких экранов */
        @media (max-width: 480px) {
            .hero h2 {
                font-size: 1.8rem;
            }

            .hero p {
                font-size: 1rem;
            }

            .about p, .services p, .contact p {
                font-size: 0.9rem;
                max-width: 95%;
            }
        }
    </style>
</head>
<body>
    <header>
        <h1>Developer Reva</h1>
        <nav>
            <a href="#about">О нас</a>
            <a href="#services">Услуги</a>
            <a href="#contact">Контакты</a>
        </nav>
    </header>

    <div class="hero">
        <h2>Добро пожаловать в Kent Studio</h2>
        <p class="typing">Мы создаем высококачественных ботов. Мы заботимся о ваших идеях!</p>
    </div>

    <div id="about" class="section about">
        <h3>О нас</h3>
        <p>Мы команда опытных разработчиков, которая специализируется на создании инновационных решений для бизнеса. Наша цель — помочь вам расти и развиваться в цифровом мире.</p>
    </div>

    <div id="services" class="section services">
        <h3>Наши услуги</h3>
        <p>Мы предлагаем широкий спектр услуг, включая разработку сайтов, создание мобильных приложений и настройку серверов. Мы всегда открыты для новых идей и проектов.</p>
    </div>

    <div id="contact" class="section contact">
        <h3>Контакты</h3>
        <p>Если у вас есть вопросы или предложения, не стесняйтесь связаться с нами. Мы всегда готовы помочь вам!</p>

        <div class="manager-buttons">
            <a href="https://t.me/fagerewaader" target="_blank">Менеджер #1</a>
            <a href="https://t.me/Nometacoder" target="_blank">Менеджер #2</a>
        </div>
    </div>

    <footer>
        <p>&copy; 2025 Kent Studio. Все права защищены.</p>
    </footer>

</body>
</html>
